No changes
RodsmonsterPC/KodeAwardsReact pull request #5
Opened 2022-10-05 23:39 UTC by BastianBV

2022-10-05 23:57 UTC, alepaez-dev requested changes

2022-10-05 23:57 UTC, alepaez-dev commented on src/components/Buttons/Google.js
> +const Google = () => {
Lo ideal de React es hacer un componente que se adapte a todo tipo de situaciones. Este boton se podria combinar con todos los de la carpeta de Buttons y te ahorras Github.js, Google.js, IniciarSesion.js .
```suggestion
const Google = ({text, className}) => {
return (
    <div className={`${styles.container}`}>
        <Button variant="outlined" className={`${styles[className]}`}>{text}</Button>
    </div>
  )
}

export default Google
```

2022-10-06 00:14 UTC, alepaez-dev requested changes

2022-10-06 00:14 UTC, alepaez-dev commented on src/components/Buttons/Github.js
> +      <Button variant="outlined" className={`${styles.buttonMicrosoft}`}>Github</Button>
Lo mismo que el comentario de Google.js

2022-10-06 00:14 UTC, alepaez-dev commented on src/components/Buttons/Google.js
> +const Google = () => {
Lo ideal de React es hacer un componente que se adapte a todo tipo de situaciones. Este boton se podria combinar con todos los de la carpeta de Buttons y te ahorras Github.js, Google.js, IniciarSesion.js .
```suggestion
const Google = () => {
return (
    <div className={`${styles.container}`}>
        <Button variant="outlined" className={`${styles[className]}`}>{text}</Button>
    </div>
  )
}
export default Google
```

2022-10-06 00:14 UTC, alepaez-dev commented on src/components/Buttons/IniciarSesion.js
> +      <Button variant="outlined" className={`${styles.buttonSesion}`}>Iniciar sesión</Button>
lo mismo x3

2022-10-06 00:14 UTC, alepaez-dev commented on src/components/Buttons/buttons.module.scss
> +  margin-top: 90px !important;
te recomiendo que apenas que lo necesiten uses el `!important`. Luego te puedo ocasionar bastantes conflictos con css

2022-10-06 00:14 UTC, alepaez-dev commented on src/components/Inputs/Email.js
> +        <input
Wachate el comentario de buttons que te hice mas arriba, es el mismo show aqui tmb

2022-10-06 00:14 UTC, alepaez-dev commented on src/components/Inputs/Password.js
> +      type="text"
```suggestion
      type="password"
```

2022-10-06 00:14 UTC, alepaez-dev commented on src/components/Inputs/PasswordConfirm.js
> +      type="text"
```suggestion
      type="password"
```

2022-10-06 00:14 UTC, alepaez-dev commented on src/components/LoginWithApp/LoginApp.js
> +        <input
Me imagino que aqui pondras tus componentes <Input /> despues

2022-10-06 00:14 UTC, alepaez-dev commented on src/components/Register/Register.js
> +      <Password/>
Esto es mas que nada un tip y estilos de cada quien. No me queda claro Email, Name, Password a lectura de simple vista. Yo les agregaria el InputEmail, etc. Cuando soluciones lo que te comente arriba simplemente te quedara `<Input text="Email"/>`, etc y solucionas esto tmb

2022-10-07 03:12 UTC, BastianBV commented on src/components/Register/Register.js
> +      <Password/>
Se soluciono haciendo solo un componente reutilizable para los inputs

2022-10-07 03:12 UTC, BastianBV commented on src/components/LoginWithApp/LoginApp.js
> +        <input
si, ya esta hecho

2022-10-07 03:13 UTC, BastianBV commented on src/components/Inputs/PasswordConfirm.js
> +      type="text"
aqui tengo mis dudas, si tengo que usar el type="password" lo debo enviar como props tambien type?

2022-10-07 03:13 UTC, BastianBV commented on src/components/Inputs/Email.js
> +        <input
Solucionado

2022-10-07 03:14 UTC, BastianBV commented on src/components/Buttons/Google.js
> +const Google = () => {
Solucionado, se hizo un solo componente reutilizable

2022-10-07 03:14 UTC, BastianBV commented on src/components/Inputs/Password.js
> +      type="text"
La misma duda que la de abajo

2022-10-07 15:18 UTC, alepaez-dev approved these changes
Nice, aprendes rápido 🚀

2022-10-07 18:12 UTC, alepaez-dev commented on src/components/Inputs/PasswordConfirm.js
> +      type="text"
Creo que esto te lo respondi por slack, si contesto mas rapido ahi. Sip, type deberia ser una prop

2022-10-07 22:24 UTC, BastianBV commented on src/components/Inputs/Password.js
> +      type="text"
Resuelto falta hacer prs

2022-10-07 22:27 UTC, merged